### ISSUE TITLE
4章のnuxt-blog-serviceでyarn generateするとTypeError発生

### ISSUE THREAD

**Issue by WO8TimeSpace175ZERO2** [potato4d/nuxt-beginners-guide#9]
4章のnuxt-blog-serviceでyarn generateすると次のようなエラーが吐かれてビルドに失敗する。

 INFO  Generating pages

× error  GEN ERR  /posts

TypeError: Cannot read property 'headers' of undefined
    at module.exports.__webpack_exports__.default (app/middleware/auth-cookie.js:10:0)
    at promisify (.nuxt/utils.js:230:0)
    at middlewareSeries (.nuxt/utils.js:210:0)
    at module.exports.__webpack_exports__.default (.nuxt/server.js:144:0)
    at _tickCallback (internal/process/next_tick.js:43:7)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
× error  GEN ERR  /posts/new

TypeError: Cannot read property 'headers' of undefined
    at module.exports.__webpack_exports__.default (app/middleware/auth-cookie.js:10:0)
    at promisify (.nuxt/utils.js:230:0)
    at middlewareSeries (.nuxt/utils.js:210:0)
    at module.exports.__webpack_exports__.default (.nuxt/server.js:144:0)
    at _tickCallback (internal/process/next_tick.js:43:7)
    at listOnTimeout (timers.js:294:7)
    at processTimers (timers.js:268:5)
× error  GEN ERR  /

TypeError: Cannot read property 'headers' of undefined
    at module.exports.__webpack_exports__.default (app/middleware/auth-cookie.js:10:0)
    at promisify (.nuxt/utils.js:230:0)
    at middlewareSeries (.nuxt/utils.js:210:0)
    at module.exports.__webpack_exports__.default (.nuxt/server.js:144:0)
Done in 37.98s.

**Comment by potato4d** [comment]
@WO8TimeSpace175ZERO2 

報告ありがとうございます。
Nuxt.js の middleware は、 generate モードでは生成時に処理を行うようになっているため、前提としてサーバーサイドの Cookie のコードはクライアント専用に書き換えていただく必要があります。

現在実際にお試しいただいているサンプルコードを提出いただければどういった状況なのかをこちらでみることはできますが、処理としてそもそも generate が想定されていないため、この Issue 自体はクローズさせていただきます。

もし generate の場合の解決をご希望の場合は、この Issue に引き続きコメントを下さい！

**Comment by WO8TimeSpace175ZERO2** [comment]
お返事ありがとうございます。
どうやら、私の修行不足が原因のようですね。
ちょっとしばらく（2019年の1月末辺りまで）某試験の勉強で忙しいため、
調査が出来ないのですが、時間が出来たら、もうちょっと調べてみます。

ただ、Angularだと開発していたものをプロダクトビルドしても、結構うまく行くような気がしますが。。。

宜しくお願い致します。
